-- ============================================================
-- Programs V3: 新增 ~100 个项目，重点覆盖欧洲大陆
-- 总计约 150 个项目（原 50 + 新增 100）
-- ============================================================

-- ===== 德国 (12个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Technical University of Munich', '慕尼黑工业大学', 'MSc Informatics', '信息学硕士', 'master', 'Germany', 37, 'Department of Informatics', '2年', '€300/学期（注册费）', '{"ielts_min":6.5,"toefl_min":88}', 3.0, false, '{"winter":"2027-05-31","summer":"2026-11-30"}', 'https://www.tum.de', '{"transcript","cv","motivation_letter","recommendation_1","ielts"}', '{"stem","免学费","欧洲名校","双非友好"}', 'TUM信息学，德国第一工科大学，几乎免学费', 'CS', '授课型', 78.0, '{"ielts_min":6.5,"toefl_min":88}', '€10,000-12,000/年', '["DAAD奖学金","TUM奖学金(€300/月)"]', false, 5, null, '德国免学费教育体系；对双非友好但需要较好成绩；课程多为英语授课'),

('Technical University of Munich', '慕尼黑工业大学', 'MSc Data Engineering and Analytics', '数据工程与分析硕士', 'master', 'Germany', 37, 'Department of Informatics', '2年', '€300/学期', '{"ielts_min":6.5,"toefl_min":88}', 3.2, false, '{"winter":"2027-05-31"}', 'https://www.tum.de', '{"transcript","cv","motivation_letter","recommendation_1","ielts"}', '{"stem","免学费","数据科学"}', 'TUM数据工程与分析，大数据方向强', 'Data Science', '授课型', 80.0, '{"ielts_min":6.5,"toefl_min":88}', '€10,000-12,000/年', '["DAAD奖学金"]', false, 5, null, '偏数据工程方向；需要数学和编程基础'),

('Ludwig Maximilian University of Munich', '慕尼黑大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 54, 'Institute for Informatics', '2年', '€300/学期', '{"ielts_min":6.5,"toefl_min":88}', 3.0, false, '{"winter":"2027-05-15","summer":"2026-11-15"}', 'https://www.lmu.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","双非友好"}', 'LMU CS硕士，慕尼黑双子星之一', 'CS', '授课型', 75.0, '{"ielts_min":6.5,"toefl_min":88}', '€10,000-12,000/年', '["DAAD奖学金","LMU-CSC联合奖学金"]', false, 4, null, '比TUM偏理论研究；对双非背景相对友好'),

('RWTH Aachen University', '亚琛工业大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 106, 'Department of Computer Science', '2年', '€300/学期', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"winter":"2027-03-01","summer":"2026-09-01"}', 'https://www.rwth-aachen.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","工科强校","双非友好"}', 'RWTH亚琛CS，德国TU9工科联盟', 'CS', '授课型', 74.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-11,000/年', '["DAAD奖学金"]', false, 4, null, '德国TU9联盟；工业界认可度极高；申请需APS审核'),

('Technical University of Berlin', '柏林工业大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 154, 'Faculty of Electrical Engineering and Computer Science', '2年', '€300/学期', '{"ielts_min":6.5,"toefl_min":88}', 2.8, false, '{"winter":"2027-05-15","summer":"2026-11-15"}', 'https://www.tu-berlin.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","柏林","双非友好","低门槛"}', '柏林工大CS，柏林创业氛围强', 'CS', '授课型', 72.0, '{"ielts_min":6.5,"toefl_min":88}', '€10,000-12,000/年', '["DAAD奖学金","Deutschlandstipendium(€300/月)"]', false, 3, null, '柏林生活成本适中；创业生态活跃；对双非友好'),

('Heidelberg University', '海德堡大学', 'MSc Data and Computer Science', '数据与计算机科学硕士', 'master', 'Germany', 47, 'Faculty of Mathematics and Computer Science', '2年', '€1,500/学期', '{"ielts_min":6.5,"toefl_min":90}', 3.2, false, '{"winter":"2027-04-15"}', 'https://www.uni-heidelberg.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","研究型","名校"}', '海德堡大学，德国最古老大学，研究实力强', 'Data Science', '研究型', 78.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-11,000/年', '["DAAD奖学金"]', false, 4, null, '巴登-符腾堡州收取非欧盟学生学费；研究导向强'),

('KIT - Karlsruhe Institute of Technology', '卡尔斯鲁厄理工学院', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 119, 'Department of Informatics', '2年', '€1,500/学期', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"winter":"2027-03-15","summer":"2026-09-15"}', 'https://www.kit.edu', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","工科强校","双非友好"}', 'KIT CS硕士，德国顶尖理工院校', 'CS', '授课型', 73.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-10,000/年', '["DAAD奖学金"]', false, 3, null, '巴登-符腾堡州收取非欧盟学生学费；TU9成员'),

('University of Stuttgart', '斯图加特大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 285, 'Faculty of Computer Science', '2年', '€1,500/学期', '{"ielts_min":6.0,"toefl_min":80}', 2.8, false, '{"winter":"2027-03-15"}', 'https://www.uni-stuttgart.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","双非友好","低门槛"}', '斯图加特CS，汽车工业重镇', 'CS', '授课型', 70.0, '{"ielts_min":6.0,"toefl_min":80}', '€9,000-10,000/年', '["DAAD奖学金"]', false, 2, null, '巴符州学费；工业界联系紧密（奔驰、保时捷总部）'),

('Humboldt University of Berlin', '柏林洪堡大学', 'MSc Data Science', '数据科学硕士', 'master', 'Germany', 120, 'Department of Computer Science', '2年', '€300/学期', '{"ielts_min":6.5,"toefl_min":88}', 3.0, false, '{"winter":"2027-05-31"}', 'https://www.hu-berlin.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","柏林","双非友好"}', '洪堡大学数据科学，柏林学术中心', 'Data Science', '授课型', 73.0, '{"ielts_min":6.5,"toefl_min":88}', '€10,000-12,000/年', '["DAAD奖学金","Einstein Foundation Fellowship"]', false, 3, null, '免学费；与柏林其他高校学分互认'),

('University of Freiburg', '弗莱堡大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 192, 'Department of Computer Science', '2年', '€1,500/学期', '{"ielts_min":6.5,"toefl_min":88}', 2.8, false, '{"winter":"2027-04-30"}', 'https://www.uni-freiburg.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","AI"}', '弗莱堡CS，AI与机器人领域强', 'CS', '授课型', 70.0, '{"ielts_min":6.5,"toefl_min":88}', '€8,500-10,000/年', '["DAAD奖学金"]', false, 2, null, '巴符州学费；机器人与AI研究实力强'),

('TU Darmstadt', '达姆施塔特工业大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Germany', 246, 'Department of Computer Science', '2年', '€300/学期', '{"ielts_min":6.0,"toefl_min":80}', 2.8, false, '{"winter":"2027-03-01"}', 'https://www.tu-darmstadt.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","双非友好","低门槛"}', 'TU Darmstadt CS，网络安全方向强', 'CS', '授课型', 70.0, '{"ielts_min":6.0,"toefl_min":80}', '€9,000-10,000/年', '["DAAD奖学金"]', false, 2, null, '免学费；TU9成员；网络安全研究欧洲领先'),

('FAU Erlangen-Nürnberg', '埃尔朗根-纽伦堡大学', 'MSc Artificial Intelligence', '人工智能硕士', 'master', 'Germany', 208, 'Department of Computer Science', '2年', '€300/学期', '{"ielts_min":6.5,"toefl_min":85}', 2.8, false, '{"winter":"2027-05-15"}', 'https://www.fau.de', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","AI","双非友好","低门槛"}', 'FAU人工智能硕士，新开设的AI专项', 'CS', '授课型', 68.0, '{"ielts_min":6.5,"toefl_min":85}', '€8,000-10,000/年', '["DAAD奖学金"]', false, 2, null, '免学费；西门子医疗总部所在地；工业合作多');

-- ===== 荷兰 (10个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Delft University of Technology', '代尔夫特理工大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Netherlands', 47, 'Faculty of EEMCS', '2年', '€18,750/年', '{"ielts_min":6.5,"toefl_min":90}', 3.2, false, '{"deadline":"2027-02-01"}', 'https://www.tudelft.nl', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","欧洲名校","工科强校"}', 'TU Delft CS，荷兰理工第一', 'CS', '授课型', 80.0, '{"ielts_min":6.5,"toefl_min":90}', '€12,000-14,000/年', '["TU Delft Excellence Scholarship(学费全免+€12,500/年)","Holland Scholarship(€5,000)"]', false, 5, null, '荷兰理工类第一；申请竞争激烈；工程方向欧洲顶尖'),

('University of Amsterdam', '阿姆斯特丹大学', 'MSc Artificial Intelligence', '人工智能硕士', 'master', 'Netherlands', 53, 'Faculty of Science', '2年', '€17,900/年', '{"ielts_min":7.0,"toefl_min":100}', 3.3, false, '{"deadline":"2027-02-01"}', 'https://www.uva.nl', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","AI","欧洲名校"}', 'UvA人工智能硕士，欧洲AI研究重镇', 'CS', '授课型', 79.0, '{"ielts_min":7.0,"toefl_min":100}', '€13,000-15,000/年', '["Amsterdam Excellence Scholarship(€25,000)","Holland Scholarship(€5,000)"]', false, 4, null, '欧洲最早的AI学位项目之一；阿姆斯特丹生活成本较高'),

('Eindhoven University of Technology', '埃因霍温理工大学', 'MSc Computer Science and Engineering', '计算机科学与工程硕士', 'master', 'Netherlands', 124, 'Department of Mathematics and Computer Science', '2年', '€17,500/年', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-05-01"}', 'https://www.tue.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","工科"}', 'TU/e CS，与ASML/飞利浦紧密合作', 'CS', '授课型', 74.0, '{"ielts_min":6.5,"toefl_min":90}', '€11,000-13,000/年', '["TU/e Scholarship(学费减免)","Holland Scholarship(€5,000)"]', false, 3, null, '与高科技产业紧密合作（ASML、飞利浦）；对双非友好'),

('Leiden University', '莱顿大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Netherlands', 126, 'Leiden Institute of Advanced Computer Science', '2年', '€18,300/年', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-04-01"}', 'https://www.universiteitleiden.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","研究型"}', '莱顿大学CS，荷兰最古老大学', 'CS', '授课型', 74.0, '{"ielts_min":6.5,"toefl_min":90}', '€12,000-14,000/年', '["Leiden University Excellence Scholarship","Holland Scholarship(€5,000)"]', false, 3, null, '荷兰最古老大学；海牙附近；研究氛围浓厚'),

('Utrecht University', '乌得勒支大学', 'MSc Business Informatics', '商业信息学硕士', 'master', 'Netherlands', 107, 'Department of Information and Computing Sciences', '2年', '€17,800/年', '{"ielts_min":6.5,"toefl_min":93}', 3.0, false, '{"deadline":"2027-04-01"}', 'https://www.uu.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"商科","stem","双非友好"}', '乌得勒支商业信息学，IT与商业交叉', 'Data Science', '授课型', 73.0, '{"ielts_min":6.5,"toefl_min":93}', '€11,000-13,000/年', '["Utrecht Excellence Scholarship","Holland Scholarship(€5,000)"]', false, 3, null, '荷兰第四大城市；生活成本适中；IT与商业交叉方向'),

('University of Groningen', '格罗宁根大学', 'MSc Computing Science', '计算科学硕士', 'master', 'Netherlands', 139, 'Faculty of Science and Engineering', '2年', '€16,200/年', '{"ielts_min":6.5,"toefl_min":90}', 2.8, false, '{"deadline":"2027-05-01"}', 'https://www.rug.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","性价比高"}', '格罗宁根CS，北荷兰性价比之选', 'CS', '授课型', 70.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-11,000/年', '["Eric Bleumink Scholarship(全额)","Holland Scholarship(€5,000)"]', false, 2, null, '生活成本低；奖学金机会多；对双非非常友好'),

('Erasmus University Rotterdam', '鹿特丹伊拉斯姆斯大学', 'MSc Business Information Management', '商业信息管理硕士', 'master', 'Netherlands', 176, 'Rotterdam School of Management', '1年', '€22,800/年', '{"ielts_min":6.5,"toefl_min":91}', 3.3, true, '{"deadline":"2027-05-01"}', 'https://www.rsm.nl', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","名校商学院"}', 'RSM商业信息管理，欧洲顶级商学院', 'Business', '授课型', 78.0, '{"ielts_min":6.5,"toefl_min":91}', '€12,000-14,000/年', '["RSM Scholarship(€10,000-20,000)","Holland Scholarship(€5,000)"]', false, 4, null, 'RSM是欧洲顶尖商学院；需要GMAT；1年制项目'),

('VU Amsterdam', '阿姆斯特丹自由大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Netherlands', 207, 'Department of Computer Science', '2年', '€16,600/年', '{"ielts_min":6.5,"toefl_min":92}', 2.8, false, '{"deadline":"2027-04-01"}', 'https://www.vu.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛"}', 'VU CS，阿姆斯特丹第二大学', 'CS', '授课型', 70.0, '{"ielts_min":6.5,"toefl_min":92}', '€13,000-15,000/年', '["VU Fellowship Programme(学费减免)","Holland Scholarship(€5,000)"]', false, 2, null, '与UvA学分互认；阿姆斯特丹就业机会多'),

('University of Twente', '特文特大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Netherlands', 210, 'Faculty of EEMCS', '2年', '€16,750/年', '{"ielts_min":6.5,"toefl_min":90}', 2.8, false, '{"deadline":"2027-05-01"}', 'https://www.utwente.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","创业"}', '特文特CS，创业氛围最强的荷兰大学', 'CS', '授课型', 68.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-11,000/年', '["University of Twente Scholarship(€3,000-25,000)"]', false, 2, null, '荷兰最具创业精神的大学；校园型大学；生活成本低'),

('Wageningen University', '瓦赫宁根大学', 'MSc Data Science for Food and Health', '食品与健康数据科学硕士', 'master', 'Netherlands', 151, 'Department of Mathematical and Statistical Methods', '2年', '€18,600/年', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-05-01"}', 'https://www.wur.nl', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","特色专业","数据科学"}', '瓦大数据科学，食品与健康交叉', 'Data Science', '授课型', 72.0, '{"ielts_min":6.5,"toefl_min":90}', '€10,000-12,000/年', '["Africa Scholarship Programme","WUR Scholarship"]', false, 3, null, '食品与农业领域世界第一；数据科学方向跨学科');

-- ===== 瑞典 (6个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('KTH Royal Institute of Technology', '瑞典皇家理工学院', 'MSc Computer Science', '计算机科学硕士', 'master', 'Sweden', 73, 'School of EECS', '2年', 'SEK 155,000/年(约€14,000)', '{"ielts_min":6.5,"toefl_min":90}', 3.2, false, '{"deadline":"2027-01-15"}', 'https://www.kth.se', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","欧洲名校","北欧"}', 'KTH CS硕士，北欧理工第一', 'CS', '授课型', 79.0, '{"ielts_min":6.5,"toefl_min":90}', 'SEK 100,000/年(约€9,000)', '["KTH Scholarship(学费全免)","SI Scholarship(学费+生活费)"]', false, 4, null, '北欧理工类第一；通过Universityadmissions.se统一申请'),

('Lund University', '隆德大学', 'MSc Machine Learning, Systems and Control', '机器学习、系统与控制硕士', 'master', 'Sweden', 75, 'Faculty of Engineering', '2年', 'SEK 145,000/年(约€13,000)', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-01-15"}', 'https://www.lunduniversity.lu.se', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","AI","北欧","双非友好"}', '隆德大学ML，北欧综合实力最强', 'CS', '授课型', 76.0, '{"ielts_min":6.5,"toefl_min":90}', 'SEK 95,000/年(约€8,500)', '["Lund University Global Scholarship","SI Scholarship"]', false, 4, null, '瑞典最古老最负盛名的大学；统一申请平台'),

('Uppsala University', '乌普萨拉大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Sweden', 105, 'Department of Information Technology', '2年', 'SEK 145,000/年(约€13,000)', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-01-15"}', 'https://www.uu.se', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","北欧"}', '乌普萨拉CS，瑞典最古老大学', 'CS', '授课型', 73.0, '{"ielts_min":6.5,"toefl_min":90}', 'SEK 90,000/年(约€8,000)', '["Uppsala University Scholarship","SI Scholarship"]', false, 3, null, '北欧最古老大学；对双非友好'),

('Chalmers University of Technology', '查尔姆斯理工大学', 'MSc Computer Science and Engineering', '计算机科学与工程硕士', 'master', 'Sweden', 125, 'Department of Computer Science and Engineering', '2年', 'SEK 160,000/年(约€14,500)', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-01-15"}', 'https://www.chalmers.se', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","工科强校","北欧","双非友好"}', '查尔姆斯CSE，瑞典工科名校', 'CS', '授课型', 75.0, '{"ielts_min":6.5,"toefl_min":90}', 'SEK 85,000/年(约€7,500)', '["Chalmers IPOET Scholarship(学费75%减免)","SI Scholarship"]', false, 3, null, '哥德堡所在；沃尔沃总部；工业联系紧密'),

('Stockholm University', '斯德哥尔摩大学', 'MSc Computer and Systems Sciences', '计算机与系统科学硕士', 'master', 'Sweden', 118, 'Department of Computer and Systems Sciences', '2年', 'SEK 130,000/年(约€12,000)', '{"ielts_min":6.5,"toefl_min":90}', 2.8, false, '{"deadline":"2027-01-15"}', 'https://www.su.se', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","北欧"}', '斯德哥尔摩大学CS，首都名校', 'CS', '授课型', 70.0, '{"ielts_min":6.5,"toefl_min":90}', 'SEK 100,000/年(约€9,000)', '["SI Scholarship","Stockholm University Scholarship"]', false, 3, null, '首都优势；与KTH部分课程共享'),

('University of Gothenburg', '哥德堡大学', 'MSc Data Science', '数据科学硕士', 'master', 'Sweden', 187, 'Department of Computer Science and Engineering', '2年', 'SEK 145,000/年(约€13,000)', '{"ielts_min":6.5,"toefl_min":90}', 2.8, false, '{"deadline":"2027-01-15"}', 'https://www.gu.se', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","数据科学","双非友好","低门槛","北欧"}', '哥德堡大学DS，与查尔姆斯联合', 'Data Science', '授课型', 68.0, '{"ielts_min":6.5,"toefl_min":90}', 'SEK 85,000/年(约€7,500)', '["SI Scholarship","University of Gothenburg Scholarship"]', false, 2, null, '与查尔姆斯理工联合办学；生活成本比斯德哥尔摩低');

-- ===== 丹麦 (5个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Technical University of Denmark', '丹麦技术大学', 'MSc Computer Science and Engineering', '计算机科学与工程硕士', 'master', 'Denmark', 121, 'Department of Applied Mathematics and Computer Science', '2年', 'DKK 67,500/学期(约€18,000/年)', '{"ielts_min":6.5,"toefl_min":88}', 3.2, false, '{"deadline":"2027-01-15"}', 'https://www.dtu.dk', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","欧洲名校","北欧"}', 'DTU CSE，北欧理工类顶尖', 'CS', '授课型', 79.0, '{"ielts_min":6.5,"toefl_min":88}', 'DKK 80,000/年(约€11,000)', '["DTU Scholarship(学费全免+生活费)"]', false, 4, null, '丹麦理工类第一；哥本哈根附近；工业界合作密切'),

('University of Copenhagen', '哥本哈根大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Denmark', 76, 'Department of Computer Science', '2年', 'DKK 60,000/学期(约€16,000/年)', '{"ielts_min":6.5,"toefl_min":90}', 3.3, false, '{"deadline":"2027-01-15"}', 'https://www.ku.dk', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","名校","北欧"}', '哥本哈根大学CS，北欧顶尖综合大学', 'CS', '授课型', 78.0, '{"ielts_min":6.5,"toefl_min":90}', 'DKK 80,000/年(约€11,000)', '["UCPH Scholarship"]', false, 4, null, '北欧综合排名最高；自然科学研究强'),

('Aarhus University', '奥胡斯大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Denmark', 132, 'Department of Computer Science', '2年', 'DKK 60,000/学期(约€16,000/年)', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-01-15"}', 'https://www.au.dk', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","北欧"}', '奥胡斯CS，丹麦第二大城市', 'CS', '授课型', 74.0, '{"ielts_min":6.5,"toefl_min":90}', 'DKK 70,000/年(约€9,500)', '["Aarhus University Scholarship"]', false, 3, null, '丹麦第二大学；生活成本比哥本哈根低；对双非友好'),

('Copenhagen Business School', '哥本哈根商学院', 'MSc Business Administration and Data Science', '工商管理与数据科学硕士', 'master', 'Denmark', 0, 'Department of Digitalization', '2年', 'DKK 65,000/学期(约€17,500/年)', '{"ielts_min":7.0,"toefl_min":100}', 3.3, true, '{"deadline":"2027-03-01"}', 'https://www.cbs.dk', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","数据科学","名校商学院"}', 'CBS商业与数据科学，北欧顶级商学院', 'Business', '授课型', 78.0, '{"ielts_min":7.0,"toefl_min":100}', 'DKK 80,000/年(约€11,000)', '["CBS Scholarship"]', false, 4, null, '三重认证商学院(AACSB/EQUIS/AMBA)；需要GMAT'),

('Aalborg University', '奥尔堡大学', 'MSc Software Engineering', '软件工程硕士', 'master', 'Denmark', 326, 'Department of Computer Science', '2年', 'DKK 52,000/学期(约€14,000/年)', '{"ielts_min":6.5,"toefl_min":88}', 2.8, false, '{"deadline":"2027-03-01"}', 'https://www.en.aau.dk', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","PBL教学"}', '奥尔堡软工，PBL问题导向教学模式', 'CS', '授课型', 66.0, '{"ielts_min":6.5,"toefl_min":88}', 'DKK 60,000/年(约€8,000)', '["AAU Scholarship"]', false, 1, null, '以PBL(问题导向学习)闻名；生活成本低；门槛友好');

-- ===== 瑞士 (5个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('ETH Zurich', '苏黎世联邦理工学院', 'MSc Computer Science', '计算机科学硕士', 'master', 'Switzerland', 7, 'Department of Computer Science', '1.5-2年', 'CHF 730/学期(约€760)', '{"ielts_min":7.0,"toefl_min":100}', 3.6, true, '{"deadline":"2026-12-15"}', 'https://www.ethz.ch', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gre"}', '{"stem","世界顶尖","低学费","高门槛"}', 'ETH CS，世界顶级理工院校，学费极低', 'CS', '研究型', 88.0, '{"ielts_min":7.0,"toefl_min":100}', 'CHF 22,000/年(约€23,000)', '["Excellence Scholarship(CHF 12,000/学期+学费全免)","ESOP Scholarship"]', false, 5, '["985","211"]', '世界排名前10；学费极低但生活成本高；竞争极其激烈；偏好985/211'),

('EPFL', '洛桑联邦理工学院', 'MSc Computer Science', '计算机科学硕士', 'master', 'Switzerland', 12, 'School of Computer and Communication Sciences', '2年', 'CHF 730/学期(约€760)', '{"ielts_min":7.0,"toefl_min":100}', 3.5, false, '{"deadline":"2027-01-15","late":"2027-04-15"}', 'https://www.epfl.ch', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","世界顶尖","低学费","高门槛"}', 'EPFL CS，瑞士法语区理工名校', 'CS', '研究型', 86.0, '{"ielts_min":7.0,"toefl_min":100}', 'CHF 20,000/年(约€21,000)', '["EPFL Excellence Fellowship(CHF 16,000/学期)"]', false, 5, null, '世界排名前15；学费极低；有late admission通道'),

('University of Zurich', '苏黎世大学', 'MSc Data Science', '数据科学硕士', 'master', 'Switzerland', 83, 'Department of Informatics', '2年', 'CHF 1,440/学期(约€1,500)', '{"ielts_min":7.0,"toefl_min":100}', 3.2, false, '{"deadline":"2027-02-28"}', 'https://www.uzh.ch', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","数据科学","低学费"}', '苏黎世大学数据科学，性价比极高', 'Data Science', '授课型', 78.0, '{"ielts_min":7.0,"toefl_min":100}', 'CHF 22,000/年(约€23,000)', '["UZH Scholarship"]', false, 4, null, '苏黎世是金融中心；就业前景好；学费极低'),

('University of Basel', '巴塞尔大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Switzerland', 142, 'Department of Mathematics and Computer Science', '2年', 'CHF 850/学期(约€880)', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-04-01"}', 'https://www.unibas.ch', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","低学费","双非友好","低门槛"}', '巴塞尔CS，瑞士北部性价比之选', 'CS', '授课型', 72.0, '{"ielts_min":6.5,"toefl_min":90}', 'CHF 18,000/年(约€19,000)', '["Swiss Government Excellence Scholarship"]', false, 2, null, '瑞法德三国交界；学费极低；门槛相对友好'),

('University of St. Gallen', '圣加仑大学', 'Master in Strategy and International Management', '战略与国际管理硕士', 'master', 'Switzerland', 0, 'School of Management', '1.5年', 'CHF 3,326/学期(约€3,500)', '{"ielts_min":7.0,"toefl_min":100}', 3.5, true, '{"deadline":"2027-03-01"}', 'https://www.unisg.ch', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","名校商学院","高门槛"}', '圣加仑SIM，连续多年FT排名全球第一', 'Business', '授课型', 85.0, '{"ielts_min":7.0,"toefl_min":100}', 'CHF 22,000/年(约€23,000)', '["HSG Scholarship"]', false, 5, null, 'FT全球管理学硕士排名多年第一；需要GMAT；竞争极其激烈');

-- ===== 法国 (6个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Sciences Po', '巴黎政治学院', 'Master in Digital, New Technology and Public Policy', '数字技术与公共政策硕士', 'master', 'France', 0, 'School of Public Affairs', '2年', '€14,500/年', '{"ielts_min":7.0,"toefl_min":100}', 3.3, false, '{"deadline":"2027-01-08"}', 'https://www.sciencespo.fr', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"社科","名校","科技政策"}', 'Sciences Po数字技术与公共政策，文理交叉', 'Other', '授课型', 78.0, '{"ielts_min":7.0,"toefl_min":100}', '€12,000-14,000/年', '["Sciences Po Scholarship(学费减免)","Emile Boutmy Scholarship"]', false, 4, null, '法国顶尖社科院校；适合文科转科技方向'),

('HEC Paris', '巴黎高等商学院', 'MSc Data Science for Business', '商业数据科学硕士', 'master', 'France', 0, 'HEC Paris & Ecole Polytechnique', '2年', '€22,000/年', '{"ielts_min":7.0,"toefl_min":100}', 3.5, true, '{"deadline":"2027-04-30"}', 'https://www.hec.edu', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","数据科学","名校商学院","高门槛"}', 'HEC×X联合数据科学，欧洲顶级商学院', 'Data Science', '授课型', 84.0, '{"ielts_min":7.0,"toefl_min":100}', '€14,000-16,000/年', '["HEC Foundation Scholarship","Eiffel Scholarship"]', false, 5, null, '欧洲商学院三巨头之一；与综合理工联合项目；需要GMAT'),

('Sorbonne University', '索邦大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'France', 59, 'Faculty of Science and Engineering', '2年', '€3,770/年', '{"ielts_min":6.5,"toefl_min":90}', 3.2, false, '{"deadline":"2027-03-31"}', 'https://www.sorbonne-universite.fr', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","低学费","名校"}', '索邦大学CS，巴黎学术中心', 'CS', '授课型', 77.0, '{"ielts_min":6.5,"toefl_min":90}', '€12,000-14,000/年', '["Eiffel Scholarship(€1,181/月)","MIEM Scholarship"]', false, 4, null, '法国公立大学学费极低；但部分课程可能含法语；Campus France程序'),

('Ecole Polytechnique', '巴黎综合理工学院', 'MSc&T Internet of Things: Innovation and Management', '物联网创新与管理硕士', 'master', 'France', 46, 'Department of Computer Science', '2年', '€15,900/年', '{"ielts_min":6.5,"toefl_min":90}', 3.3, false, '{"round1":"2027-01-08","round2":"2027-03-05","round3":"2027-05-08"}', 'https://www.polytechnique.edu', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","名校","物联网","创业"}', '综合理工IoT，法国最顶尖工程院校', 'CS', '授课型', 80.0, '{"ielts_min":6.5,"toefl_min":90}', '€12,000-14,000/年', '["Polytechnique Scholarship(学费减免+生活费)","Eiffel Scholarship"]', false, 5, null, '法国理工类第一；军事化管理传统；多轮次录取'),

('ESSEC Business School', 'ESSEC商学院', 'MSc in Data Sciences & Business Analytics', '数据科学与商业分析硕士', 'master', 'France', 0, 'ESSEC & CentraleSupélec', '1年', '€23,800', '{"ielts_min":7.0,"toefl_min":100}', 3.3, true, '{"deadline":"2027-04-15"}', 'https://www.essec.edu', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","数据科学","名校商学院"}', 'ESSEC×CentraleSupélec联合DS&BA', 'Data Science', '授课型', 80.0, '{"ielts_min":7.0,"toefl_min":100}', '€14,000-16,000/年', '["ESSEC Foundation Scholarship","Eiffel Scholarship"]', false, 4, null, '法国排名前三商学院；1年制密集项目；需要GMAT/GRE'),

('Toulouse School of Economics', '图卢兹经济学院', 'MSc Statistics and Econometrics', '统计与计量经济学硕士', 'master', 'France', 0, 'Department of Economics', '2年', '€5,000/年', '{"ielts_min":6.5,"toefl_min":90}', 3.2, true, '{"deadline":"2027-04-01"}', 'https://www.tse-fr.eu', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gre"}', '{"stem","经济学","低学费","研究型"}', 'TSE统计与计量，经济学领域世界前十', 'Data Science', '研究型', 80.0, '{"ielts_min":6.5,"toefl_min":90}', '€8,000-10,000/年', '["TSE Scholarship(学费全免)","Eiffel Scholarship"]', false, 4, null, '经济学研究世界前列；图卢兹生活成本低；适合读博跳板');

-- ===== 爱尔兰 (4个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Trinity College Dublin', '都柏林圣三一学院', 'MSc Computer Science', '计算机科学硕士', 'master', 'Ireland', 81, 'School of Computer Science and Statistics', '1年', '€25,800', '{"ielts_min":6.5,"toefl_min":90}', 3.2, false, '{"deadline":"2027-05-31"}', 'https://www.tcd.ie', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","欧洲名校","英语国家"}', 'TCD CS硕士，爱尔兰最好的大学', 'CS', '授课型', 78.0, '{"ielts_min":6.5,"toefl_min":90}', '€12,000-14,000/年', '["Provost PhD Project Awards","TCD Scholarship"]', false, 4, null, '爱尔兰第一；都柏林是欧洲科技之都(Google/Meta/Apple总部)；1年制'),

('University College Dublin', '都柏林大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Ireland', 126, 'School of Computer Science', '1年', '€23,800', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"round1":"2027-01-31","round2":"2027-05-31"}', 'https://www.ucd.ie', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","双非友好","英语国家"}', 'UCD CS硕士，爱尔兰最大大学', 'CS', '授课型', 74.0, '{"ielts_min":6.5,"toefl_min":90}', '€11,000-13,000/年', '["Global Excellence Scholarship(€4,000)","Science Scholarship"]', false, 3, null, '爱尔兰最大大学；科技公司实习机会多；对双非友好'),

('University of Galway', '高威大学', 'MSc Computer Science - Data Analytics', '计算机科学-数据分析硕士', 'master', 'Ireland', 259, 'School of Computer Science', '1年', '€18,500', '{"ielts_min":6.5,"toefl_min":90}', 2.8, false, '{"deadline":"2027-06-30"}', 'https://www.universityofgalway.ie', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","英语国家","性价比高"}', '高威大学数据分析，爱尔兰西海岸', 'Data Science', '授课型', 68.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-11,000/年', '["University of Galway Scholarship"]', true, 2, null, '生活成本低；滚动录取；Medtronic等医疗科技公司总部'),

('Dublin City University', '都柏林城市大学', 'MSc in Computing', '计算机硕士', 'master', 'Ireland', 421, 'School of Computing', '1年', '€17,600', '{"ielts_min":6.5,"toefl_min":92}', 2.8, false, '{"deadline":"2027-06-30"}', 'https://www.dcu.ie', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","英语国家","性价比高"}', 'DCU Computing硕士，实践导向强', 'CS', '授课型', 66.0, '{"ielts_min":6.5,"toefl_min":92}', '€10,000-12,000/年', '["DCU Scholarship"]', true, 1, null, '实践导向；与行业紧密合作；滚动录取；门槛友好');

-- ===== 芬兰 (3个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Aalto University', '阿尔托大学', 'MSc Computer, Communication and Information Sciences', '计算机、通信与信息科学硕士', 'master', 'Finland', 109, 'School of Science', '2年', '€15,000/年', '{"ielts_min":6.5,"toefl_min":92}', 3.2, false, '{"deadline":"2027-01-03"}', 'https://www.aalto.fi', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","北欧","设计+科技"}', 'Aalto CS硕士，设计思维与科技融合', 'CS', '授课型', 78.0, '{"ielts_min":6.5,"toefl_min":92}', '€10,000-12,000/年', '["Aalto University Scholarship(学费全免)","Finland Scholarship"]', false, 4, null, '设计思维与工程结合；Nokia渊源；赫尔辛基生态'),

('University of Helsinki', '赫尔辛基大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Finland', 107, 'Department of Computer Science', '2年', '€15,000/年', '{"ielts_min":6.5,"toefl_min":92}', 3.0, false, '{"deadline":"2027-01-10"}', 'https://www.helsinki.fi', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","北欧","双非友好"}', '赫尔辛基大学CS，芬兰最高学府', 'CS', '授课型', 75.0, '{"ielts_min":6.5,"toefl_min":92}', '€10,000-12,000/年', '["Helsinki University Scholarship(学费全免)"]', false, 3, null, '芬兰排名第一；CS教育质量极高；对双非友好'),

('Tampere University', '坦佩雷大学', 'MSc Software, Web and Cloud', '软件、Web与云计算硕士', 'master', 'Finland', 284, 'Faculty of Information Technology and Communication Sciences', '2年', '€12,000/年', '{"ielts_min":6.5,"toefl_min":92}', 2.8, false, '{"deadline":"2027-01-12"}', 'https://www.tuni.fi', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","双非友好","低门槛","北欧","性价比高"}', '坦佩雷软件与云计算，芬兰第二大学城', 'CS', '授课型', 68.0, '{"ielts_min":6.5,"toefl_min":92}', '€8,000-10,000/年', '["Tampere University Scholarship(学费50-100%减免)"]', false, 2, null, '生活成本低；学费奖学金机会多；门槛友好');

-- ===== 意大利 (3个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('Politecnico di Milano', '米兰理工大学', 'MSc Computer Science and Engineering', '计算机科学与工程硕士', 'master', 'Italy', 111, 'Department of Electronics, Information and Bioengineering', '2年', '€3,900/年', '{"ielts_min":6.0,"toefl_min":78}', 3.0, false, '{"round1":"2027-01-20","round2":"2027-03-09"}', 'https://www.polimi.it', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","低学费","欧洲名校","双非友好"}', '米兰理工CSE，意大利理工第一，学费极低', 'CS', '授课型', 76.0, '{"ielts_min":6.0,"toefl_min":78}', '€10,000-12,000/年', '["Politecnico di Milano Merit Scholarship(€10,000/年)","DSU Scholarship"]', false, 4, null, '意大利理工第一；学费极低；时尚之都米兰；多轮次录取'),

('Bocconi University', '博科尼大学', 'MSc in Data Science and Business Analytics', '数据科学与商业分析硕士', 'master', 'Italy', 0, 'Department of Decision Sciences', '2年', '€14,990/年', '{"ielts_min":7.0,"toefl_min":100}', 3.4, true, '{"round1":"2027-01-13","round2":"2027-03-24","round3":"2027-05-26"}', 'https://www.unibocconi.eu', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","数据科学","名校商学院"}', '博科尼DSBA，欧洲顶级商学院', 'Data Science', '授课型', 82.0, '{"ielts_min":7.0,"toefl_min":100}', '€12,000-14,000/年', '["Bocconi Merit Award(学费全免+€12,000/年)","ISU Bocconi"]', false, 5, null, '欧洲商学院Top5；需要GMAT/GRE；多轮次录取'),

('University of Bologna', '博洛尼亚大学', 'MSc Artificial Intelligence', '人工智能硕士', 'master', 'Italy', 164, 'Department of Computer Science and Engineering', '2年', '€2,700/年', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"round1":"2027-02-01","round2":"2027-04-30"}', 'https://www.unibo.it', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","AI","低学费","双非友好","历史名校"}', '博洛尼亚AI硕士，世界最古老大学', 'CS', '授课型', 72.0, '{"ielts_min":6.5,"toefl_min":90}', '€8,000-10,000/年', '["Unibo Scholarship(学费全免+€11,000/年)"]', false, 3, null, '世界最古老大学(创建于1088年)；学费极低；AI方向新兴强势');

-- ===== 西班牙 (2个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('IE University', 'IE大学', 'Master in Business Analytics and Big Data', '商业分析与大数据硕士', 'master', 'Spain', 0, 'IE School of Science and Technology', '10个月', '€46,200', '{"ielts_min":7.0,"toefl_min":100}', 3.3, true, '{"round1":"2026-10-15","round2":"2027-01-15","round3":"2027-04-15","round4":"2027-06-15"}', 'https://www.ie.edu', '{"transcript","cv","motivation_letter","recommendation_2","ielts","gmat"}', '{"商科","数据科学","名校商学院","高门槛"}', 'IE商业分析与大数据，全球顶级商学院', 'Business', '授课型', 82.0, '{"ielts_min":7.0,"toefl_min":100}', '€12,000-14,000/年', '["IE Talent & Excellence Scholarship(25-100%学费)"]', false, 4, null, '全球Top10商学院；马德里；10个月高密度项目；多轮次录取'),

('Universitat Pompeu Fabra', '庞培法布拉大学', 'MSc Data Science', '数据科学硕士', 'master', 'Spain', 178, 'Department of Information and Communication Technologies', '1年', '€10,050', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-05-31"}', 'https://www.upf.edu', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","数据科学","巴塞罗那","性价比高"}', 'UPF数据科学，巴塞罗那学术新贵', 'Data Science', '授课型', 72.0, '{"ielts_min":6.5,"toefl_min":90}', '€10,000-12,000/年', '["UPF Scholarship"]', false, 3, null, '巴塞罗那；西班牙社科类排名第一；性价比高');

-- ===== 挪威 (2个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('University of Oslo', '奥斯陆大学', 'MSc Informatics: Programming and System Architecture', '信息学：编程与系统架构硕士', 'master', 'Norway', 113, 'Department of Informatics', '2年', '免学费', '{"ielts_min":6.5,"toefl_min":90}', 3.2, false, '{"deadline":"2027-02-01"}', 'https://www.uio.no', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","北欧","名校"}', '奥斯陆大学CS，挪威免学费教育', 'CS', '授课型', 76.0, '{"ielts_min":6.5,"toefl_min":90}', 'NOK 130,000/年(约€11,500)', '["Quota Scheme Scholarship"]', false, 4, null, '挪威完全免学费（含国际生）；但生活成本高'),

('Norwegian University of Science and Technology', '挪威科技大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Norway', 135, 'Department of Computer Science', '2年', '免学费', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-02-01"}', 'https://www.ntnu.edu', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","免学费","北欧","双非友好"}', 'NTNU CS，挪威理工第一', 'CS', '授课型', 73.0, '{"ielts_min":6.5,"toefl_min":90}', 'NOK 120,000/年(约€10,500)', '["Quota Scheme Scholarship"]', false, 3, null, '挪威理工类第一；完全免学费；特隆赫姆生活成本比奥斯陆低');

-- ===== 比利时 (2个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('KU Leuven', '鲁汶大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Belgium', 61, 'Department of Computer Science', '2年', '€3,570/年', '{"ielts_min":7.0,"toefl_min":94}', 3.2, false, '{"deadline":"2027-03-01"}', 'https://www.kuleuven.be', '{"transcript","cv","motivation_letter","recommendation_2","ielts"}', '{"stem","低学费","欧洲名校"}', 'KU Leuven CS，比利时第一、欧洲顶尖', 'CS', '授课型', 79.0, '{"ielts_min":7.0,"toefl_min":94}', '€10,000-12,000/年', '["Science@Leuven Scholarship(学费全免+€10,000/年)","VLIR-UOS Scholarship"]', false, 4, null, '比利时排名第一；欧洲创新型大学联盟成员；学费极低'),

('Ghent University', '根特大学', 'MSc Computer Science Engineering', '计算机科学工程硕士', 'master', 'Belgium', 152, 'Faculty of Engineering and Architecture', '2年', '€3,570/年', '{"ielts_min":6.5,"toefl_min":90}', 3.0, false, '{"deadline":"2027-03-01"}', 'https://www.ugent.be', '{"transcript","cv","motivation_letter","ielts"}', '{"stem","低学费","双非友好"}', '根特大学CS工程，比利时第二', 'CS', '授课型', 74.0, '{"ielts_min":6.5,"toefl_min":90}', '€9,000-11,000/年', '["BOF Scholarship","VLIR-UOS Scholarship"]', false, 3, null, '比利时第二大学；学费极低；根特是大学城');

-- ===== 加拿大 (4个，新增地区) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('University of Toronto', '多伦多大学', 'MScAC - Master of Science in Applied Computing', '应用计算科学硕士', 'master', 'Canada', 21, 'Department of Computer Science', '16个月', 'CAD 54,840/年', '{"ielts_min":7.0,"toefl_min":93}', 3.5, false, '{"deadline":"2027-01-15"}', 'https://www.utoronto.ca', '{"transcript","cv","sop","recommendation_3","ielts"}', '{"stem","名校","含实习","高门槛"}', 'UofT MScAC，8个月课程+8个月带薪实习', 'CS', '授课型', 82.0, '{"ielts_min":7.0,"toefl_min":93}', 'CAD 18,000/年', '["University of Toronto Fellowship"]', false, 5, null, '加拿大第一；含8个月带薪实习；竞争激烈'),

('University of British Columbia', '英属哥伦比亚大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Canada', 34, 'Department of Computer Science', '2年', 'CAD 9,131/年(含奖)', '{"ielts_min":7.0,"toefl_min":100}', 3.3, false, '{"deadline":"2026-12-15"}', 'https://www.cs.ubc.ca', '{"transcript","cv","sop","recommendation_3","ielts"}', '{"stem","名校","研究型"}', 'UBC CS硕士，温哥华名校', 'CS', '研究型', 80.0, '{"ielts_min":7.0,"toefl_min":100}', 'CAD 16,000/年', '["Graduate Funding Package"]', false, 5, null, '研究型硕士；通常含全额资助；温哥华生活成本高'),

('University of Waterloo', '滑铁卢大学', 'MMath Computer Science', '计算机科学数学硕士', 'master', 'Canada', 112, 'David R. Cheriton School of Computer Science', '2年', 'CAD 8,700/学期', '{"ielts_min":7.0,"toefl_min":100}', 3.3, false, '{"deadline":"2027-02-01"}', 'https://cs.uwaterloo.ca', '{"transcript","cv","sop","recommendation_3","ielts"}', '{"stem","CS强校","co-op"}', '滑铁卢CS，加拿大CS最强', 'CS', '研究型', 81.0, '{"ielts_min":7.0,"toefl_min":100}', 'CAD 14,000/年', '["Graduate Research Studentship"]', false, 4, null, '加拿大CS综合实力最强；co-op项目闻名；研究型为主'),

('McGill University', '麦吉尔大学', 'MSc Computer Science', '计算机科学硕士', 'master', 'Canada', 30, 'School of Computer Science', '2年', 'CAD 8,000/学期', '{"ielts_min":6.5,"toefl_min":86}', 3.3, false, '{"deadline":"2026-12-15"}', 'https://www.cs.mcgill.ca', '{"transcript","cv","sop","recommendation_3","ielts"}', '{"stem","名校","蒙特利尔","AI"}', '麦吉尔CS，Mila AI研究所所在', 'CS', '研究型', 80.0, '{"ielts_min":6.5,"toefl_min":86}', 'CAD 12,000/年', '["MILA Scholarship","Graduate Funding"]', false, 5, null, 'Mila(世界最大AI研究所)所在；蒙特利尔生活成本低');

-- ===== 补充英国 (5个，增加专业多样性) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('University of Edinburgh', '爱丁堡大学', 'MSc Education', '教育学硕士', 'master', 'UK', 22, 'Moray House School of Education and Sport', '1年', '£28,800/年', '{"ielts_min":7.0,"toefl_min":100}', 3.2, false, '{"round1":"2026-12-01","round2":"2027-03-01"}', 'https://www.ed.ac.uk', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"教育","名校","双非友好"}', '爱丁堡教育学硕士，教育方向强', 'Education', '授课型', 74.0, '{"ielts_min":7.0,"toefl_min":100}', '£12,000-14,000/年', '["Edinburgh Global Scholarship"]', false, 4, null, '教育学专业排名英国前5；适合转专业申请'),

('University of Manchester', '曼彻斯特大学', 'MA Digital Media, Culture and Society', '数字媒体、文化与社会硕士', 'master', 'UK', 32, 'School of Arts, Languages and Cultures', '1年', '£24,500/年', '{"ielts_min":7.0,"toefl_min":100}', 3.0, false, '{"deadline":"2027-06-30"}', 'https://www.manchester.ac.uk', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"传媒","双非友好","跨专业"}', '曼大数字媒体，适合文科生转向数字媒体', 'Other', '授课型', 70.0, '{"ielts_min":7.0,"toefl_min":100}', '£10,000-12,000/年', '["Manchester Master Scholarship"]', true, 3, null, '适合传媒/文科背景转数字方向；滚动录取'),

('University of Warwick', '华威大学', 'MSc Marketing and Strategy', '市场营销与战略硕士', 'master', 'UK', 69, 'Warwick Business School', '1年', '£35,400/年', '{"ielts_min":7.0,"toefl_min":100}', 3.3, false, '{"round1":"2026-10-15","round2":"2027-01-15","round3":"2027-03-31"}', 'https://www.wbs.ac.uk', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"商科","名校商学院"}', '华威商学院市场营销与战略', 'Business', '授课型', 78.0, '{"ielts_min":7.0,"toefl_min":100}', '£11,000-13,000/年', '["WBS Scholarship"]', false, 4, null, '华威商学院英国Top5；多轮次录取'),

('University of Leeds', '利兹大学', 'MA Communication and Media', '传播与媒体硕士', 'master', 'UK', 75, 'School of Media and Communication', '1年', '£26,750/年', '{"ielts_min":6.5,"toefl_min":92}', 3.0, false, '{"deadline":"2027-06-30"}', 'https://www.leeds.ac.uk', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"传媒","双非友好","低门槛"}', '利兹传媒，英国传媒专业Top3', 'Other', '授课型', 70.0, '{"ielts_min":6.5,"toefl_min":92}', '£9,000-11,000/年', '["Leeds Masters Scholarship(£5,000)"]', true, 3, null, '英国传媒专业前三；对双非友好；滚动录取'),

('University of Bath', '巴斯大学', 'MSc Accounting and Finance', '会计与金融硕士', 'master', 'UK', 148, 'School of Management', '1年', '£30,000/年', '{"ielts_min":7.0,"toefl_min":100}', 3.3, false, '{"round1":"2026-11-30","round2":"2027-02-28","round3":"2027-05-31"}', 'https://www.bath.ac.uk', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"商科","会计金融","双非友好"}', '巴斯会计与金融，英国AF专业前5', 'Business', '授课型', 76.0, '{"ielts_min":7.0,"toefl_min":100}', '£9,000-11,000/年', '["Bath International Scholarship"]', false, 3, null, '会计金融专业英国排名前5；多轮次录取');

-- ===== 补充美国 (5个，增加专业多样性) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('University of Pennsylvania', '宾夕法尼亚大学', 'MSE in Data Science', '数据科学工程硕士', 'master', 'US', 11, 'School of Engineering and Applied Science', '1.5年', '$56,000/年', '{"toefl_min":100,"ielts_min":7.5}', 3.5, true, '{"deadline":"2027-01-15"}', 'https://dats.seas.upenn.edu', '{"transcript","sop","cv","recommendation_3","toefl","gre"}', '{"stem","名校","数据科学","高门槛"}', 'UPenn数据科学，藤校工程学院', 'Data Science', '授课型', 85.0, '{"toefl_min":100,"ielts_min":7.5}', '$18,000-20,000/年', '["Penn Engineering Scholarship"]', false, 5, '["985"]', '藤校光环；STEM OPT；竞争激烈'),

('University of Washington', '华盛顿大学', 'MS Information Management', '信息管理硕士', 'master', 'US', 63, 'Information School', '2年', '$38,000/年', '{"toefl_min":92,"ielts_min":7.0}', 3.2, false, '{"deadline":"2027-01-15"}', 'https://ischool.uw.edu', '{"transcript","sop","cv","recommendation_3","toefl"}', '{"stem","双非友好","西雅图","热门"}', 'UW iSchool信息管理，西雅图科技中心', 'Data Science', '授课型', 76.0, '{"toefl_min":92,"ielts_min":7.0}', '$16,000-18,000/年', '["iSchool Scholarship"]', false, 4, null, '西雅图（Amazon/Microsoft总部）；不需要GRE；对双非相对友好'),

('Purdue University', '普渡大学', 'MS Computer Science', '计算机科学硕士', 'master', 'US', 99, 'Department of Computer Science', '2年', '$32,000/年', '{"toefl_min":90,"ielts_min":6.5}', 3.2, true, '{"deadline":"2026-12-20"}', 'https://www.cs.purdue.edu', '{"transcript","sop","cv","recommendation_3","toefl","gre"}', '{"stem","CS强校","性价比高","双非友好"}', '普渡CS，美国老牌工科名校', 'CS', '授课型', 76.0, '{"toefl_min":90,"ielts_min":6.5}', '$12,000-14,000/年', '["Purdue Fellowship"]', false, 3, null, '美国工科传统强校；性价比极高；对双非友好'),

('Arizona State University', '亚利桑那州立大学', 'MS Computer Science', '计算机科学硕士', 'master', 'US', 179, 'School of Computing and Augmented Intelligence', '2年', '$32,000/年', '{"toefl_min":80,"ielts_min":6.5}', 3.0, true, '{"round1":"2027-01-01","round2":"2027-04-01"}', 'https://scai.engineering.asu.edu', '{"transcript","sop","cv","recommendation_3","toefl","gre"}', '{"stem","双非友好","低门槛","创新"}', 'ASU CS，全美创新第一', 'CS', '授课型', 70.0, '{"toefl_min":80,"ielts_min":6.5}', '$12,000-14,000/年', '["ASU Graduate Scholarship"]', false, 2, null, '全美创新排名第一(超过MIT和斯坦福)；门槛友好'),

('Rutgers University', '罗格斯大学', 'MS Data Science', '数据科学硕士', 'master', 'US', 262, 'Department of Statistics', '2年', '$35,000/年', '{"toefl_min":83,"ielts_min":7.0}', 3.0, true, '{"deadline":"2027-04-15"}', 'https://www.stat.rutgers.edu', '{"transcript","sop","cv","recommendation_3","toefl","gre"}', '{"stem","双非友好","低门槛","纽约周边"}', 'Rutgers数据科学，纽约都会区', 'Data Science', '授课型', 68.0, '{"toefl_min":83,"ielts_min":7.0}', '$14,000-16,000/年', '["Rutgers Fellowship"]', false, 2, null, '新泽西州立；近纽约；门槛友好；性价比高');

-- ===== 补充澳洲 (3个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('University of Melbourne', '墨尔本大学', 'Master of Education', '教育学硕士', 'master', 'Australia', 14, 'Melbourne Graduate School of Education', '2年', 'AUD 39,000/年', '{"ielts_min":7.0,"toefl_min":94}', 3.0, false, '{}', 'https://education.unimelb.edu.au', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"教育","名校","双非友好","移民加分"}', '墨大教育硕士，教育学全球第一', 'Education', '授课型', 74.0, '{"ielts_min":7.0,"toefl_min":94}', 'AUD 22,000-26,000/年', '["Melbourne Graduate Scholarship"]', true, 5, null, '教育学全球排名第一；可申请教师注册；滚动录取'),

('University of New South Wales', '新南威尔士大学', 'Master of Finance', '金融硕士', 'master', 'Australia', 19, 'UNSW Business School', '1.5年', 'AUD 49,000/年', '{"ielts_min":7.0,"toefl_min":94}', 3.3, false, '{}', 'https://www.business.unsw.edu.au', '{"transcript","sop","cv","ielts"}', '{"商科","名校","金融中心"}', 'UNSW金融硕士，悉尼金融中心', 'Business', '授课型', 78.0, '{"ielts_min":7.0,"toefl_min":94}', 'AUD 22,000-26,000/年', '["UNSW Scholarship"]', true, 4, null, '悉尼金融行业就业强；滚动录取'),

('Macquarie University', '麦考瑞大学', 'Master of Data Science', '数据科学硕士', 'master', 'Australia', 130, 'School of Computing', '2年', 'AUD 38,400/年', '{"ielts_min":6.5,"toefl_min":83}', 2.8, false, '{}', 'https://www.mq.edu.au', '{"transcript","cv","ielts"}', '{"stem","数据科学","双非友好","低门槛"}', '麦考瑞数据科学，悉尼北区', 'Data Science', '授课型', 68.0, '{"ielts_min":6.5,"toefl_min":83}', 'AUD 20,000-24,000/年', '["MQIS Scholarship(AUD 10,000)"]', true, 2, null, '悉尼北区科技园区；对双非友好；门槛低');

-- ===== 补充香港 (2个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('The University of Hong Kong', '香港大学', 'MSc Business Analytics', '商业分析硕士', 'master', 'Hong Kong', 17, 'Faculty of Business and Economics', '1年', 'HKD 330,000', '{"ielts_min":7.0,"toefl_min":100}', 3.5, true, '{"round1":"2026-10-16","round2":"2027-01-14","round3":"2027-03-14"}', 'https://www.hku.hk', '{"transcript","sop","cv","recommendation_2","ielts","gmat"}', '{"商科","名校","数据科学","高门槛"}', 'HKU商业分析，港大商学院', 'Business', '授课型', 82.0, '{"ielts_min":7.0,"toefl_min":100}', 'HKD 80,000-100,000/年', '["HKU Entrance Scholarship"]', false, 5, '["985","211"]', '港大商学院；需要GMAT/GRE；偏好985/211'),

('City University of Hong Kong', '香港城市大学', 'MSc Marketing', '市场营销硕士', 'master', 'Hong Kong', 62, 'College of Business', '1年', 'HKD 195,000', '{"ielts_min":6.5,"toefl_min":79}', 3.0, false, '{"round1":"2026-11-15","round2":"2027-02-15","round3":"2027-04-15"}', 'https://www.cityu.edu.hk', '{"transcript","sop","cv","recommendation_2","ielts"}', '{"商科","双非友好"}', '城大市场营销，性价比高', 'Business', '授课型', 72.0, '{"ielts_min":6.5,"toefl_min":79}', 'HKD 60,000-80,000/年', '["CityU Scholarship"]', false, 3, null, '对双非友好；多轮次录取');

-- ===== 补充新加坡 (2个) =====

INSERT INTO public.programs (university_name, university_name_cn, program_name, program_name_cn, degree_type, country, qs_ranking, department, duration, tuition, language_requirement, gpa_requirement, gre_required, deadline, application_link, required_materials, tags, description, field, program_type, avg_score, require_lang, living_cost, scholarship, rolling_admission, prestige, accept_list, notes)
VALUES
('National University of Singapore', '新加坡国立大学', 'MSc Business Analytics', '商业分析硕士', 'master', 'Singapore', 8, 'School of Computing', '1年', 'SGD 48,000', '{"ielts_min":6.0,"toefl_min":85}', 3.3, true, '{"deadline":"2027-03-31"}', 'https://msba.nus.edu.sg', '{"transcript","sop","cv","recommendation_2","ielts","gmat"}', '{"商科","数据科学","名校","亚洲顶尖"}', 'NUS商业分析，亚洲第一大学', 'Data Science', '授课型', 82.0, '{"ielts_min":6.0,"toefl_min":85}', 'SGD 16,000-20,000/年', '["NUS Merit Scholarship"]', false, 5, '["985","211"]', 'NUS计算机学院下的商业分析；需要GMAT/GRE；偏好985/211'),

('Nanyang Technological University', '南洋理工大学', 'MSc Marketing Science', '营销科学硕士', 'master', 'Singapore', 15, 'Nanyang Business School', '1年', 'SGD 42,000', '{"ielts_min":6.5,"toefl_min":100}', 3.2, true, '{"deadline":"2027-03-31"}', 'https://www.ntu.edu.sg/business', '{"transcript","sop","cv","recommendation_2","ielts","gmat"}', '{"商科","名校"}', 'NTU营销科学，商学院强势项目', 'Business', '授课型', 78.0, '{"ielts_min":6.5,"toefl_min":100}', 'SGD 14,000-18,000/年', '["NTU Scholarship"]', false, 4, null, '南洋商学院亚洲排名前列；需要GMAT');
